# Generated by Django 5.2 on 2026-01-22 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
