# Generated by Django 5.2 on 2026-02-07 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_room_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rooms_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
