# Generated by Django 5.2 on 2026-02-10 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_created_at_booking_status'),
        ('hotels', '0004_rename_quantity_room_stock_alter_hotel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotels.room'),
        ),
    ]
