# Generated by Django 5.2 on 2026-01-22 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_room_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guest_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
