# Generated by Django 5.2 on 2026-02-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_room_guest_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='quantity',
            new_name='stock',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
